# Ada Boost Classifier

In [2]:
import sklearn.ensemble
sklearn.ensemble.__all__



['BaseEnsemble',
 'RandomForestClassifier',
 'RandomForestRegressor',
 'RandomTreesEmbedding',
 'ExtraTreesClassifier',
 'ExtraTreesRegressor',
 'BaggingClassifier',
 'BaggingRegressor',
 'IsolationForest',
 'GradientBoostingClassifier',
 'GradientBoostingRegressor',
 'AdaBoostClassifier',
 'AdaBoostRegressor',
 'VotingClassifier',
 'VotingRegressor',
 'StackingClassifier',
 'StackingRegressor']

In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
dataset = load_iris()

x = pd.DataFrame(dataset['data'], columns = dataset['feature_names'])
y = dataset.target

In [5]:
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3)

In [7]:
model = AdaBoostClassifier()
model.__dict__

{'base_estimator': None,
 'n_estimators': 50,
 'estimator_params': (),
 'learning_rate': 1.0,
 'random_state': None,
 'algorithm': 'SAMME.R'}

In [8]:
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.9333333333333333

In [9]:
pred = model.predict(x_test)

In [10]:
print(confusion_matrix(y_test, pred))

[[ 9  0  0]
 [ 0 18  2]
 [ 0  1 15]]


In [11]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.95      0.90      0.92        20
           2       0.88      0.94      0.91        16

    accuracy                           0.93        45
   macro avg       0.94      0.95      0.94        45
weighted avg       0.93      0.93      0.93        45

