# Bagging Classifier

In [1]:
import sklearn.ensemble
sklearn.ensemble.__all__



['BaseEnsemble',
 'RandomForestClassifier',
 'RandomForestRegressor',
 'RandomTreesEmbedding',
 'ExtraTreesClassifier',
 'ExtraTreesRegressor',
 'BaggingClassifier',
 'BaggingRegressor',
 'IsolationForest',
 'GradientBoostingClassifier',
 'GradientBoostingRegressor',
 'AdaBoostClassifier',
 'AdaBoostRegressor',
 'VotingClassifier',
 'VotingRegressor',
 'StackingClassifier',
 'StackingRegressor']

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
dataset = load_iris()

x = pd.DataFrame(dataset['data'], columns = dataset['feature_names'])
y = dataset.target

In [4]:
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3)

In [6]:
model = BaggingClassifier()
model.__dict__

{'base_estimator': None,
 'n_estimators': 10,
 'estimator_params': (),
 'max_samples': 1.0,
 'max_features': 1.0,
 'bootstrap': True,
 'bootstrap_features': False,
 'oob_score': False,
 'warm_start': False,
 'n_jobs': None,
 'random_state': None,
 'verbose': 0}

In [7]:
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.9555555555555556

In [8]:
pred = model.predict(x_test)

In [9]:
print(confusion_matrix(y_test, pred))

[[13  0  0]
 [ 0 15  2]
 [ 0  0 15]]


In [10]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.88      0.94        17
           2       0.88      1.00      0.94        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

