# Random Forest Classifier

In [1]:
import sklearn.ensemble
sklearn.ensemble.__all__



['BaseEnsemble',
 'RandomForestClassifier',
 'RandomForestRegressor',
 'RandomTreesEmbedding',
 'ExtraTreesClassifier',
 'ExtraTreesRegressor',
 'BaggingClassifier',
 'BaggingRegressor',
 'IsolationForest',
 'GradientBoostingClassifier',
 'GradientBoostingRegressor',
 'AdaBoostClassifier',
 'AdaBoostRegressor',
 'VotingClassifier',
 'VotingRegressor',
 'StackingClassifier',
 'StackingRegressor']

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
dataset = load_iris()

x = pd.DataFrame(dataset['data'], columns = dataset['feature_names'])
y = dataset.target

In [4]:
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3)

In [6]:
model = RandomForestClassifier()
model.__dict__

{'base_estimator': DecisionTreeClassifier(),
 'n_estimators': 100,
 'estimator_params': ('criterion',
  'max_depth',
  'min_samples_split',
  'min_samples_leaf',
  'min_weight_fraction_leaf',
  'max_features',
  'max_leaf_nodes',
  'min_impurity_decrease',
  'min_impurity_split',
  'random_state',
  'ccp_alpha'),
 'bootstrap': True,
 'oob_score': False,
 'n_jobs': None,
 'random_state': None,
 'verbose': 0,
 'warm_start': False,
 'class_weight': None,
 'max_samples': None,
 'criterion': 'gini',
 'max_depth': None,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'min_weight_fraction_leaf': 0.0,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'ccp_alpha': 0.0}

In [7]:
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.9555555555555556

In [8]:
pred = model.predict(x_test)

In [9]:
print(confusion_matrix(y_test, pred))

[[15  0  0]
 [ 0 13  1]
 [ 0  1 15]]


In [10]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.93      0.93      0.93        14
           2       0.94      0.94      0.94        16

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

