In [3]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [4]:
df = pd.read_csv("iris.data.csv")

In [5]:
df.head()

sepal_length  sepal_width  petal_length  petal_width   Class_name
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [8]:
dataset = df.drop(['Class_name'],axis = 1)
target = df['Class_name']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(dataset,target,test_size = 0.2)

In [13]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [14]:
knn.score(X_test,y_test)

1.0

In [16]:
y_pred = knn.predict(X_test)

In [17]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      1.00      1.00        12
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

[[ 7  0  0]
 [ 0 12  0]
 [ 0  0 11]]
