In [5]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [9]:
df = pd.read_csv("iris.data.csv")

In [10]:
df.head()

sepal_length  sepal_width  petal_length  petal_width   Class_name
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [11]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width      Class_name
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [13]:
df["Class_name"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [15]:
dataset = df.drop(["Class_name"],axis=1)

In [16]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [18]:
target = df["Class_name"]

In [19]:
X_train,X_test,y_train,y_test = train_test_split(dataset,target,test_size = 0.2)

In [27]:
mlp = MLPClassifier(hidden_layer_sizes=[250,], activation = "logistic",max_iter = 800)

In [28]:
X_train.head()

sepal_length  sepal_width  petal_length  petal_width
66            5.6          3.0           4.5          1.5
142           5.8          2.7           5.1          1.9
72            6.3          2.5           4.9          1.5
106           4.9          2.5           4.5          1.7
78            6.0          2.9           4.5          1.5

In [29]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=[250], max_iter=800)

In [30]:
mlp.score(X_test,y_test)

1.0

In [34]:
y_pred = mlp.predict(X_test)

In [35]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        10
 Iris-virginica       1.00      1.00      1.00        10

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
